apiVersion: v1
kind: Service
metadata:
  name: online-learning-service
spec:
  selector:
    app: online-learning
  ports:
    - protocol: TCP
      port: 4000
      targetPort: 4000
  type: NodePort 